using System;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace WFrameWork.Samples.Combined.Editor
{
    /// <summary>Checks only addresses and assets generated by the Combined sample.</summary>
    public static class CombinedSampleAddressablesValidator
    {
        private static readonly string[] Addresses =
        {
            "GFramework.Samples.Player", "GFramework.Samples.Settings",
            "GFramework.Samples.Menu", "GFramework.Samples.Config", "GFramework.Samples.Game"
        };

        [MenuItem("GFramework/Samples/Validate Combined Addressables")]
        public static void ValidateMenu() { Validate(false); }

        // Unity -batchmode -executeMethod WFrameWork.Samples.Combined.Editor.CombinedSampleAddressablesValidator.ValidateCommandLine
        public static void ValidateCommandLine() { Validate(true); }

        private static void Validate(bool throwOnError)
        {
            int errors = 0;
            AddressableAssetSettings settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Report("Addressables Settings is missing.", ref errors);
            }
            else
            {
                for (int i = 0; i < Addresses.Length; i++)
                {
                    AddressableAssetEntry entry = FindByAddress(settings, Addresses[i]);
                    if (entry == null) { Report("Missing address: " + Addresses[i], ref errors); continue; }
                    string path = AssetDatabase.GUIDToAssetPath(entry.guid);
                    if (string.IsNullOrEmpty(path)) Report("Missing asset for address: " + Addresses[i], ref errors);
                    else if (Addresses[i].EndsWith(".Game", StringComparison.Ordinal) && !path.EndsWith(".unity", StringComparison.OrdinalIgnoreCase))
                        Report("Game address is not a scene: " + path, ref errors);
                    else if (!Addresses[i].EndsWith(".Game", StringComparison.Ordinal) && !path.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase) && !path.EndsWith(".asset", StringComparison.OrdinalIgnoreCase))
                        Report("Sample address has an unexpected asset type: " + Addresses[i], ref errors);
                }
            }
            string generatedScene = "Assets/GFrameworkSamples/Combined/Scenes/CombinedSample.unity";
            if (!AssetDatabase.LoadAssetAtPath<SceneAsset>(generatedScene)) Report("Generated Combined scene is missing: " + generatedScene, ref errors);
            if (errors > 0 && throwOnError) throw new InvalidOperationException("Combined Addressables validation failed with " + errors + " error(s).");
            if (errors == 0) Debug.Log("GFramework combined Addressables validation passed.");
        }

        private static void Report(string message, ref int errors)
        { errors++; Debug.LogError("[GFramework Combined] " + message); }

        private static AddressableAssetEntry FindByAddress(AddressableAssetSettings settings, string address)
        {
            foreach (AddressableAssetGroup group in settings.groups)
            {
                if (group == null) continue;
                foreach (AddressableAssetEntry entry in group.entries)
                    if (entry != null && string.Equals(entry.address, address, StringComparison.Ordinal)) return entry;
            }
            return null;
        }
    }
}
